STM32MP1 experimental support

diff --git a/debian/bin/u-boot-install b/debian/bin/u-boot-install
--- a/debian/bin/u-boot-install
+++ b/debian/bin/u-boot-install
@@ -125,9 +125,51 @@ function install_sunxi64
 	sync ${DEV}
 }
 
+function install_stm32mp1xx
+{
+	DEV=$1
+	SPL="/usr/lib/u-boot-olinuxino/${TARGET}/u-boot-spl.stm32"
+
+	if [[ ! -e ${SPL} ]]; then
+		echo >&2 "$0: the file \'${SPL}\' is missing"
+		exit 1
+	fi
+
+	UBOOT="/usr/lib/u-boot-olinuxino/${TARGET}/u-boot.img"
+
+	if [[ ! -e ${UBOOT} ]]; then
+		echo >&2 "$0: the file \'${UBOOT}\' is missing"
+		exit 1
+	fi
+
+	# Try to detect the root device
+	if [[ -z ${DEV} ]]; then
+		DEV=$(get_root_device)
+		if [[ -z ${DEV} ]]; then
+			echo >&2 "$0: failed to detect the root device"
+			exit 1
+		fi
+	fi
+
+	if [[ ! -w ${DEV} ]]; then
+		echo >&2 "$0: device/image ($DEV) must be writable"
+		exit 1
+	fi
+
+	echo "Writing u-boot-spl.stm32"
+	dd if=${SPL} of=${DEV}p1
+	dd if=${SPL} of=${DEV}p2
+
+	echo "Writing u-boot.img"
+	dd if=${UBOOT} of=${DEV}p3
+
+}
+
 # Detect family
 for comp in $(cat "/proc/device-tree/compatible" | tr '\0' '\n'); do
 	if [[ "${comp}" == "allwinner,sun"* ]]; then
+		soc=$(cut -d',' -f2 <<< ${comp})
+	elif [[ "${comp}" == "st,stm32mp1"* ]]; then
 		soc=$(cut -d',' -f2 <<< ${comp})
 	elif [[ "${comp}" == "olimex,"* ]]; then
 		board="${comp}"
@@ -159,6 +201,11 @@ if [[ -z "${TARGET}" ]]; then
 		"sun50i-a64")
 			TARGET="a64-olinuxino"
 			INSTALL_FUNC=install_sunxi64
+			;;
+
+		"stm32mp1"*)
+			TARGET="stm32-olinuxino"
+			INSTALL_FUNC=install_stm32mp1xx
 			;;
 
 		*)
