debian: u-boot-install: Update supported devices

diff --git a/debian/bin/u-boot-install b/debian/bin/u-boot-install
--- a/debian/bin/u-boot-install
+++ b/debian/bin/u-boot-install
@@ -1,81 +1,86 @@
 #!/bin/sh
 set -e
 
-dtmodel="/sys/firmware/devicetree/base/model"
-if [ -z "$TARGET" ] && [ -f "${dtmodel}" ]; then
-	case $(cat "${dtmodel}" | tr '\0' '\n') in
-		"Olimex A64-Olinuxino") TARGET="/usr/lib/u-boot/a64-olinuxino/" ;;
-		"Olimex A64-Olinuxino-eMMC") TARGET="/usr/lib/u-boot/a64-olinuxino/" ;;
+# Detect family
+for comp in $(cat "/proc/device-tree/compatible" | tr '\0' '\n'); do
+	if [[ "${comp}" == "allwinner,sun"* ]]; then
+		soc=$(cut -d',' -f2 <<< ${comp})
+	elif [[ "${comp}" == "olimex,"* ]]; then
+		board="${comp}"
+	fi
+done
+
+if [[ -z "${TARGET}" ]]; then
+	case ${soc} in
+		"sun5i-a13")
+			TARGET="/usr/lib/u-boot-olinuxino/a13-olinuxino/"
+			;;
+
+		"sun7i-a20")
+			TARGET="/usr/lib/u-boot-olinuxino/a20-olinuxino/"
+			;;
+
+		"sun50i-a64")
+			TARGET="/usr/lib/u-boot-olinuxino/a64-olinuxino/"
+			;;
+
+		*)
+			echo >&2 "$0: Unsupported sunxi family: ${soc}."
+			exit 1;
+			;;
 	esac
 fi
 
-atf="/usr/lib/arm-trusted-firmware/sun50i_a64/bl31.bin"
-if [ -z "$BL31" ] && [ -f "${atf}" ]; then
-	BL31="${atf}"
-fi
+function install_sunxi
+{
+	echo "adasd"
+}
 
-TARGET=${TARGET:-"/usr/lib/u-boot/a64-olinuxino/"}
-BL31=${BL31:-"/usr/lib/arm-trusted-firmware/sun50i_a64/bl31.bin"}
-FIT_GENERATOR=${FIT_GENERATOR:-"mksunxi_fit_atf"}
+function install_sunxi64
+{
+	ATF="/usr/lib/arm-trusted-firmware/sun50i_a64/bl31.bin"
+	if [[ -z "$BL31" ]] && [[ -f "${ATF}" ]]; then
+		BL31="${atf}"
+	fi
 
-case "$1" in
-	-f|--force)
-		FORCE=y
-		shift;;
-	-*)
-		echo >&2 "$0: unknown option '$1'"
-		exit 1;;
-esac
+	BL31=${BL31:-"/usr/lib/arm-trusted-firmware-olinuxino/sun50i_a64/bl31.bin"}
+	FIT_GENERATOR=${FIT_GENERATOR:-"mksunxi_fit_atf"}
 
-if [ -z "$(which mkimage)" ]; then
-	echo >&2 "$0: mkimage: command not found. Please install u-boot-tools."
-	exit 1
-fi
 
-DEV="$1"
-if [ -z "$DEV" ] || ! shift || [ -n "$*" ]; then
-	echo >&2 "Usage: $0 /dev/your-sd-or-mmc-or-image"
-	exit 1
-fi
-
-if [ ! -w "$DEV" ] && [ -z "$FORCE" ]; then
-	echo >&2 "$0: device/image ($DEV) must be writable"
-	exit 1
-fi
-DEV="$(readlink -f "$DEV")"
-DIR="$(mktemp -d)"
-trap 'rm -rf "$DIR"' 0
-# Build tools get confused by paths, thus let's copy all the pieces into
-# one dir.
-
-if [ ! -w "$DEV" ] && [ -z "$FORCE" ]; then
-	echo >&2 "$0: device/image ($DEV) not accessible via abs path?!?"
-	exit 1
-fi
-
-cd "$DIR"
-if [ -z "$FORCE" ]; then
-	# A very simple sanity check.  GPT mandates a "protective MBR" so this works
-	# even with GPT partitioning.
-	printf '%b' '\0125\0252' >mbr-sign
-	if ! cmp -s -i 0:510 -n 2 mbr-sign "$DEV"; then
-		echo >&2 "$0: device/image ($DEV) has no MBR partition table"
+	if [[ -z "$(which mkimage)" ]]; then
+		echo >&2 "$0: mkimage: command not found. Please install u-boot-tools-olinuxino."
 		exit 1
 	fi
 
-	# But, on sunxi64, spl will trample upon GPT.
-	printf "EFI PART" >gpt-sign
-	if cmp -s -i 0:512 -n 8 gpt-sign "$DEV"; then
-		echo >&2 "$0: device/image ($DEV) uses GPT partition table, unusable on sunxi64"
+	DEV="$1"
+	if [ -z "$DEV" ] || ! shift || [ -n "$*" ]; then
+		echo >&2 "Usage: $0 /dev/your-sd-or-mmc-or-image"
 		exit 1
 	fi
-fi
 
-cp -p $TARGET/*.dtb $TARGET/*.bin .
-BL31=$BL31 $FIT_GENERATOR *.dtb > u-boot.its
-mkimage -f u-boot.its u-boot.itb
-echo "Writing sunxi-spl"
-dd conv=notrunc if=sunxi-spl.bin of="$DEV" bs=8k seek=1
-echo "Writing u-boot FIT image"
-dd conv=notrunc if=u-boot.itb of="$DEV" bs=8k seek=5
-sync "$DEV"
+	if [ ! -w "$DEV" ] && [ -z "$FORCE" ]; then
+		echo >&2 "$0: device/image ($DEV) must be writable"
+		exit 1
+	fi
+	DEV="$(readlink -f "$DEV")"
+	DIR="$(mktemp -d)"
+	trap 'rm -rf "$DIR"' 0
+	# Build tools get confused by paths, thus let's copy all the pieces into
+	# one dir.
+
+	if [ ! -w "$DEV" ] && [ -z "$FORCE" ]; then
+		echo >&2 "$0: device/image ($DEV) not accessible via abs path?!?"
+		exit 1
+	fi
+
+	cd "$DIR"
+
+	cp -p $TARGET/*.dtb $TARGET/*.bin .
+	BL31=$BL31 $FIT_GENERATOR *.dtb > u-boot.its
+	mkimage -f u-boot.its u-boot.itb
+	echo "Writing sunxi-spl"
+	dd conv=notrunc if=sunxi-spl.bin of="$DEV" bs=8k seek=1
+	echo "Writing u-boot FIT image"
+	dd conv=notrunc if=u-boot.itb of="$DEV" bs=8k seek=5
+	sync "$DEV"
+}
